In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
vec = np.arange(10, 40, 10)
vec

array([10, 20, 30])

In [9]:
mat = np.arange(1, 3 * 4 + 1).reshape(3, -1)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
vec @ mat

array([380, 440, 500, 560])

In [11]:
10 * 1 + 20 * 5 + 30 * 9

380